name: AkKenVyu
description: Serve players (who opt in) with the latest version of a resource pack from a GitHub repo.
author: SeriousGuy888
website: https://github.com/SeriousGuy888/AkKenVyu

version: '${project.version}'
api-version: '1.20'
main: io.github.seriousguy888.akkenvyu.AkKenVyu

commands:
  resourcepack:
    permission: akkenvyu.command.resourcepack
    permission-message: Insufficient permission. Ask an admin to give you the permission for this command.
    description: Toggles whether the server will send you the server resource pack.
    aliases:
      - rp
      - resources
      - pack

permissions:
  akkenvyu.command.resourcepack:
    default: op
